### ISSUE TITLE
Downloading release as zip does not populate gdifont

### ISSUE THREAD

**Issue by gthoma2** [ThornyFFXI/tCrossBar#17]
I've downloaded crossbar and installed per instructions into my addons folder. /tc didn't bring anything up and when I did 
/addon load tCrossBar the console was yelling at me that it couldnt find needed lua and dlls, all related to gdifont.

After some of my own research I found that the gdifonts directory was empty and that I had to download and populate that folder manually from the gdifont github page. When I go into the files, it looks like that git page has defaulted to a branch that isn't main?

![Screenshot 2024-11-08 192037](https://github.com/user-attachments/assets/57132ecf-3999-404e-bfc1-5f5271c8f2d4)

Maybe that's why it's not automatically populating the directory?

**Comment by ThornyFFXI** [comment]
You should be using the actual release on the right side, not downloading the repo as zip.  Gdifonts is a submodule, it will populate if you clone the git repo using an actual git tool.  Download as zip is not proper use of github in most cases, and this is expected.
