### ISSUE TITLE
Issue with BLM attack spells

### ISSUE THREAD

**Issue by alexisatauri** [ThornyFFXI/tCrossBar#18]
I had this issue come up the other week; fixed itself when I restarted/updated GPU drivers. 

Now the issue persists on both my PC and laptop. Other bindings work fine, but when I cast a spell like "Stone" or "Water" (macro, from the menu or using tcrossbar) the addon encounters an error and shuts down. 

Screenshot attached. 

![image](https://github.com/user-attachments/assets/35108db3-bf95-465d-9733-fe8cc80f0d0a)

**Comment by ThornyFFXI** [comment]
Not related to your graphics drivers, but should be fixed in 2.14.

**Comment by alexisatauri** [comment]
thanks! :)
