### ISSUE TITLE
Updated version not loading.

### ISSUE THREAD

**Issue by Watercrown** [ThornyFFXI/tCrossBar#2]
![Untitled](https://user-images.githubusercontent.com/74643708/222502865-3305558b-8414-4ce5-9b82-55a5be018841.png)

Hey Thorny.

Appreciate you taking a look at the issue I mentioned.

I attempted to update to the latest version and I am now seeing this error. I can still load the previous version just fine.

**Comment by ThornyFFXI** [comment]
If you've modified your layouts, you need to adjust them to match the current layout format.

Specifically, IconFadeAlpha and SkillchainAnimationTime are now members of the topmost table, rather than duplicated under both layouts.

**Comment by Watercrown** [comment]
Yup! Thanks.
