### ISSUE TITLE
Issue with JA client

### ISSUE THREAD

**Issue by onimitch** [ThornyFFXI/tCrossBar#4]
Hi,

First of all, thanks for making this addon!

I'm playing on Retail, with JA client. It's the JA Playonline Viewer if that makes any difference but obviously I'm launching through Ashita v4 so have the language set there too.

All I've done so far is bind a few abilities/items/ws from my level 5 THF (I'm a new/very old returning player) to a few buttons.

1. Ability names all appear with ???? in the binding GUI (I'm taking a guess maybe this is due to missing ja font? Anyway to do fix that?).
2. If I try to edit this binding, specifically delete the text inside the Macro text box, the client crashes when I get to near deleting all the text. I think a clue to the problem here is, if you look in my screenshot, it's missing the second quote for the `/ja "..."`. So some kind of encoding issue perhaps?
3. In the square overlay where you can see the icons in the grid, the names are all mangled.
4. [EDIT: This is working as long as you don't try to edit the mangled text in the IMGUI bindings UI] In the overlay, the ability icons are all ?. My guess is, there is no map for the japanese names to IDs? (Is there anywhere I can edit this?) This is probably a nice to have.

Incase it makes a difference, items show the correct icon in the overlay, but the names are mangled. They show as all ??? in the binding GUI. Text commands show fine

**Comment by onimitch** [comment]
![スクリーンショット 2023-09-18 13 53 17](https://github.com/ThornyFFXI/tCrossBar/assets/3901242/bb481b0a-6b53-4cc7-8ede-21a019e8dc00)

**Comment by onimitch** [comment]
Ah sorry, one last thing I noticed when investigating this.

If I open my bindings.lua (so in this case THF.lua) as UTF-8 (default) I see this:

![スクリーンショット 2023-09-18 14 14 59](https://github.com/ThornyFFXI/tCrossBar/assets/3901242/31e1516d-84f4-45b9-a779-9213f07c0ed0)

Re-opening the file as Shift JIS I correctly see the japanese as it should be:

![スクリーンショット 2023-09-18 14 15 18](https://github.com/ThornyFFXI/tCrossBar/assets/3901242/a81f8f81-1edf-4dcd-aa73-62d72301aaa0)

**Comment by ThornyFFXI** [comment]
As you've surmised, this is likely due to incompatibilities between encodings and missing fonts.  I am not responsible for the IMGUI implementation in Ashita, so I will need to reach out to ask about specifics.  It is likely that the display issues can be resolved, but I am less sure on support for japanese input in IMGUI, that would depend on the engine and is outside the scope of this addon.

I've noted the issue and will update as time allows.

**Comment by onimitch** [comment]
Heya. I found out how to fix the Japanese text rendering issues in tRenderer.

```
**#include <locale.h>**

void AbilitySquare::CreatePath(Gdiplus::GraphicsPath** ppGraphicsPath, GdiplusFontObject_t Font, const char* text)
{
    SAFE_DELETE(*ppGraphicsPath);

    if ((text == nullptr) || (strlen(text) == 0))
        return;

    **setlocale(LC_ALL, "");**

    wchar_t textBuffer[1024];
    swprintf_s(textBuffer, 1024, L"%S", text);
    *ppGraphicsPath = new Gdiplus::GraphicsPath();
    (*ppGraphicsPath)->AddString(textBuffer, wcslen(textBuffer), Font.FontFamily, Font.FontStyle, Font.FontHeight, Font.Rect, Font.FontFormat);
}
```

In the end I only had to add `setlocale(LC_ALL, "");`
```

With that change it's displaying english and Japanese text correctly in the Ability Squares.

IMGUI is obviously still a separate issue like you said.

Also in my original report 4 is no longer a problem. My guess is trying to edit the bindings in IMGUI causes the config to break, but if I simply create the binding without editing any of the text fields, the correct icon shows.

**Comment by onimitch** [comment]
![スクリーンショット 2023-09-22 14 24 10](https://github.com/ThornyFFXI/tCrossBar/assets/3901242/c2594b58-d74d-4657-b735-6345eef2653b)

This is using Noto Sans JP font configured in the Layout.

**Comment by ThornyFFXI** [comment]
2.00 converts all resource calls from Shift-JIS to UTF-8, calls set_locale(LC_ALL) in the renderer, and converts text back from UTF-8 to shift-JIS prior when executing macros.  This should provide full japanese language compatibility, and has been tested with the next (unreleased) version of Ashita for compatibility with IMGUI as well.  I expect some existing macros that have been written in shift-JIS may need to be altered to continue to work correctly.  This can be used with the current version of ashita, it just won't correctly show in IMGUI until the update.

I'm closing this for now, but if any new issues arise after the ashita update goes live, please open a new issue.

**Comment by onimitch** [comment]
I really appreciate this, thank you!
I'll hold off on trying the new version until 4.16 is out to the public. Looking forward to it :)
