### ISSUE TITLE
Add "/tc palette last" command

### ISSUE THREAD

**Issue by TheRealYasri** [ThornyFFXI/tCrossBar#8]
Can you add a slash command to go to the last palette used.

If your on palette 3 and use a macro with 
/tc palette change 5
Then use a macro with 
/tc palette last 
It would jump you back to 3

**Comment by ThornyFFXI** [comment]
Good idea, I'll add it this week.

**Comment by TheRealYasri** [comment]
Thanks for making such a great addon, make playing on controller so much better.

**Comment by TheRealYasri** [comment]
Thanks for making such a great addon, makes playing with a controller so much better

**Comment by ThornyFFXI** [comment]
Added in 2.08.
