### ISSUE TITLE
SCH's stratagems are always faded.

### ISSUE THREAD

**Issue by Sulryn** [ThornyFFXI/tCrossBar#9]
Icons for SCH's stratagems are always faded.
I find that there is an issue in updaters/ability.lua.
`if (type(recastReady) == 'number') then
        recastReady = (recastReady == 0);
end`
I tried change it to
`if (type(recastReady) == 'number') then
        recastReady = (recastReady > 0);
end`
I reload the addon and the change seems like it fixes the problem, since the recastReady is no longer false when it's a number larger than 0.
I don't know if it changes the other ability though...

**Comment by ThornyFFXI** [comment]
That is not a correct fix, no.  I'll put out a patch to fix it today.

**Comment by ThornyFFXI** [comment]
Actually, that should work fine, since the only time it won't be a number is for charge based abilities.  I'll double check though before pushing, since I have a few other things that I plan to add and don't see a point in multiple version changes.

**Comment by ThornyFFXI** [comment]
Resolved in 2.08.
